2023-11-18 17:40:08.657    debug login create license   
2023-11-18 17:40:08.879 ###### License error The underlying provider failed on Open.  
2023-11-18 17:40:10.183    ### [Message 0] ###   https://localhost:4341/Account/LogOff  [Stack] =  
2023-11-18 17:40:10.188    ### [Message 0] ###   One or more errors occurred.  [Stack] =    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)        at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)        at BLL.Log.LogManager..ctor()        at BLL.Log.LogManager.get_Instance()        at Sadaf.Controllers.AccountController.<LogOff>d__32.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_5.<BeginInvokeAction>b__4()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_0.<BeginInvokeAction>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)        at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()        at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)        at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)    ### [Message 1] ###   Login failed for user 'sadaf'.  [Stack] =    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)        at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.Open()        at BLL.Process.UpdateDatabase.<Update>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at BLL.Log.LogManager.<>c.<<-ctor>b__6_0>d.MoveNext() 
2023-11-18 17:40:14.671    ### [Message 0] ###   https://localhost:4341/Account/LogOff  [Stack] =  
2023-11-18 17:40:14.671    ### [Message 0] ###   One or more errors occurred.  [Stack] =    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)        at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)        at BLL.Log.LogManager..ctor()        at BLL.Log.LogManager.get_Instance()        at Sadaf.Controllers.AccountController.<LogOff>d__32.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_5.<BeginInvokeAction>b__4()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_0.<BeginInvokeAction>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)        at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()        at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)        at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)    ### [Message 1] ###   Login failed for user 'sadaf'.  [Stack] =    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)        at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.Open()        at BLL.Process.UpdateDatabase.<Update>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at BLL.Log.LogManager.<>c.<<-ctor>b__6_0>d.MoveNext() 
2023-11-18 17:40:16.315    ### [Message 0] ###   https://localhost:4341/Account/LogOff  [Stack] =  
2023-11-18 17:40:16.316    ### [Message 0] ###   One or more errors occurred.  [Stack] =    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)        at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)        at BLL.Log.LogManager..ctor()        at BLL.Log.LogManager.get_Instance()        at Sadaf.Controllers.AccountController.<LogOff>d__32.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_5.<BeginInvokeAction>b__4()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_0.<BeginInvokeAction>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)        at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()        at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)        at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)    ### [Message 1] ###   Login failed for user 'sadaf'.  [Stack] =    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)        at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.Open()        at BLL.Process.UpdateDatabase.<Update>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at BLL.Log.LogManager.<>c.<<-ctor>b__6_0>d.MoveNext() 
2023-11-18 17:40:17.043    ### [Message 0] ###   https://localhost:4341/Account/LogOff  [Stack] =  
2023-11-18 17:40:17.043    ### [Message 0] ###   One or more errors occurred.  [Stack] =    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)        at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)        at BLL.Log.LogManager..ctor()        at BLL.Log.LogManager.get_Instance()        at Sadaf.Controllers.AccountController.<LogOff>d__32.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_5.<BeginInvokeAction>b__4()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_0.<BeginInvokeAction>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)        at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()        at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)        at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)    ### [Message 1] ###   Login failed for user 'sadaf'.  [Stack] =    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)        at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.Open()        at BLL.Process.UpdateDatabase.<Update>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at BLL.Log.LogManager.<>c.<<-ctor>b__6_0>d.MoveNext() 
2023-11-18 17:41:14.893    debug login create license   
2023-11-18 17:41:15.566 ###### License error The underlying provider failed on Open.  
2023-11-18 17:41:15.806    ### [Message 0] ###   https://localhost:4341/Account/LogOff  [Stack] =  
2023-11-18 17:41:15.808    ### [Message 0] ###   One or more errors occurred.  [Stack] =    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)        at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)        at BLL.Log.LogManager..ctor()        at BLL.Log.LogManager.get_Instance()        at Sadaf.Controllers.AccountController.<LogOff>d__32.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_5.<BeginInvokeAction>b__4()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_0.<BeginInvokeAction>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)        at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()        at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)        at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)    ### [Message 1] ###   Login failed for user 'sadaf-temp'.  [Stack] =    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)        at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.Open()        at BLL.Process.UpdateDatabase.<Update>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at BLL.Log.LogManager.<>c.<<-ctor>b__6_0>d.MoveNext() 
2023-11-18 17:41:17.598    ### [Message 0] ###   https://localhost:4341/Account/LogOff  [Stack] =  
2023-11-18 17:41:17.599    ### [Message 0] ###   One or more errors occurred.  [Stack] =    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)        at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)        at BLL.Log.LogManager..ctor()        at BLL.Log.LogManager.get_Instance()        at Sadaf.Controllers.AccountController.<LogOff>d__32.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_5.<BeginInvokeAction>b__4()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_0.<BeginInvokeAction>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)        at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()        at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)        at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)    ### [Message 1] ###   Login failed for user 'sadaf-temp'.  [Stack] =    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)        at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.Open()        at BLL.Process.UpdateDatabase.<Update>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at BLL.Log.LogManager.<>c.<<-ctor>b__6_0>d.MoveNext() 
2023-11-18 17:41:18.299    ### [Message 0] ###   https://localhost:4341/Account/LogOff  [Stack] =  
2023-11-18 17:41:18.300    ### [Message 0] ###   One or more errors occurred.  [Stack] =    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)        at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)        at BLL.Log.LogManager..ctor()        at BLL.Log.LogManager.get_Instance()        at Sadaf.Controllers.AccountController.<LogOff>d__32.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_5.<BeginInvokeAction>b__4()        at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_0.<BeginInvokeAction>b__1(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)        at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)        at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()        at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)        at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)    ### [Message 1] ###   Login failed for user 'sadaf-temp'.  [Stack] =    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)        at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)        at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)        at System.Data.SqlClient.SqlConnection.Open()        at BLL.Process.UpdateDatabase.<Update>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at BLL.Log.LogManager.<>c.<<-ctor>b__6_0>d.MoveNext() 
2023-11-18 17:41:51.420    debug login create license   
2023-11-18 17:41:54.239 #### License Error incorrect customer id 
2023-11-18 17:41:54.371 ###### License error شماره مشتری شما با شماره مشتری جواز متفاوت است  
2023-11-18 17:42:02.088    ### [Message 0] ###   خطا!  [Stack] =    at Web.api.DashboardsController.<Get>d__0.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() 
2023-11-18 17:42:02.092    ### [Message 0] ###   خطا!  [Stack] =    at Web.api.DashboardsController.<Get>d__0.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() 
2023-11-18 17:42:02.099    ### [Message 0] ###   Error  [Stack] =    at BLL.ApplicationLicense.ClientLicenseManager.ExceptionIfNotValid()        at Web.api.MenusController.MenuCategories(Int32 id)        at lambda_method(Closure , Object , Object[] )        at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_0.<GetExecutor>b__2(Object instance, Object[] methodParameters)        at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() 
2023-11-18 17:42:02.100    ### [Message 0] ###   Error  [Stack] =    at BLL.ApplicationLicense.ClientLicenseManager.ExceptionIfNotValid()        at Web.api.MenusController.MenuCategories(Int32 id)        at lambda_method(Closure , Object , Object[] )        at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_0.<GetExecutor>b__2(Object instance, Object[] methodParameters)        at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() 
2023-11-18 17:42:02.155    ### [Message 0] ###   Object reference not set to an instance of an object.  [Stack] =    at Web.api.FormsController.Get(Nullable`1 packageId, String q, Boolean all)        at lambda_method(Closure , Object , Object[] )        at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_0.<GetExecutor>b__2(Object instance, Object[] methodParameters)        at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() 
2023-11-18 17:42:02.155    ### [Message 0] ###   Object reference not set to an instance of an object.  [Stack] =    at Web.api.FormsController.Get(Nullable`1 packageId, String q, Boolean all)        at lambda_method(Closure , Object , Object[] )        at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_0.<GetExecutor>b__2(Object instance, Object[] methodParameters)        at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()     --- End of stack trace from previous location where exception was thrown ---        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() 
